version: '2'
 services:
   db:  //数据库容器
     image: postgres
   web:  //web服务器容器
     build: .
     command: python manage.py runserver 0.0.0.0:8000
     volumes:   //挂载本地机器文件夹
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
       - db


       #https://www.jianshu.com/p/4d096c02d6fe