version: '3'
services:
  jenkins:
    container_name: jenkins
    hostname: jenkins
    #build:
     # context: ./jenkins
      #dockerfile: Dockerfile
    image: jenkins:latest
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ${jenkins_home}:/var/jenkins_home
      - ${maven_home}:/usr/local/maven
      - ${java_home}:/usr/local/jdk
  tomcat:     #tomcat 服务
    image: tomcat:7    #镜像
    hostname: tomcat7       #容器的主机名
    container_name: tomcat7   #容器名
    ports:      #端口
     - "5050:8081"
    volumes:  #数据卷
     - "/webapps:/usr/local/tomcat/webapps"
  dbmysql:  
    image: docker.io/mysql:5.7
    ports:  
     - 3306:3306  
    environment:  
       MYSQL_ROOT_PASSWORD: password  
    volumes:  
     - /mysql/datadir:/var/lib/mysql  
     - /mysql/conf:/etc/mysql/conf.d:ro
